version: "3.8"
services:
  consumer:
    image: image-sizing-consumer
    container_name: consumer
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env